"""All migration

Revision ID: 4424c7cd591a
Revises: 808e9c2eceff
Create Date: 2022-09-04 11:55:02.468291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4424c7cd591a'
down_revision = '808e9c2eceff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
